const soccerTeamNames = [
  "Real Madrid",
  "FC Barcelona",
  "Manchester United",
  "Liverpool FC",
  "Bayern Munich",
  "Paris Saint-Germain",
  "Juventus",
  "AC Milan",
  "Chelsea FC",
  "Manchester City",
  "Arsenal FC",
  "Borussia Dortmund",
  "Inter Milan",
  "Atletico Madrid",
  "Tottenham Hotspur",
  "Ajax Amsterdam",
  "FC Porto",
  "Roma",
  "Napoli",
  "Boca Juniors",
  "River Plate",
  "Flamengo",
  "Santos",
  "Palmeiras",
  "Cruzeiro",
  "Gremio",
  "Sao Paulo FC",
  "Benfica",
  "Sporting CP",
  "Fenerbahce",
  "Galatasaray",
  "Besiktas",
  "Olympique de Marseille",
  "AS Monaco",
  "FC Zenit Saint Petersburg",
  "Shakhtar Donetsk",
  "Celtic FC",
  "Rangers FC",
  "Anderlecht",
  "Club Brugge",
  "PSV Eindhoven",
  "Feyenoord",
  "Red Bull Salzburg",
  "Red Bull Leipzig",
  "Copenhagen",
  "AIK",
  "Rosenborg",
  "Malmo FF",
  "Dynamo Kyiv",
  "Lokomotiv Moscow",
  "Basel",
  "Young Boys",
  "Partizan Belgrade",
  "Crvena Zvezda",
  "Spartak Moscow",
  "Legia Warsaw",
  "Levski Sofia",
  "Dinamo Zagreb",
  "Olympiacos",
  "Panathinaikos",
  "PAOK",
  "AEK Athens",
];
export default soccerTeamNames;
